会员系统后台 -> WhatsApp集成/API -> WhatsApp客户端: 查询结果(提示消息 + H5页面地址)
H5前端 -> 会员系统后台: 查询请求
会员系统后台 -> 电商ERP: 查询订单
电商ERP -> 会员系统后台: 查询结果
电商ERP -> 会员系统后台: 同步新用户
电商ERP -> 会员系统后台: 查询会员信息
会员系统后台 -> 实体店POS: 查询订单
实体店POS -> 会员系统后台: 查询结果
实体店POS -> 会员系统后台: 同步新用户
实体店POS -> 会员系统后台: 查询会员信息
会员系统后台 -> WhatsApp集成/API -> WhatsApp客户端: 1. 发送消息(提示消息 + H5页面地址)
WhatsApp集成/API -> 会员系统后台: 同步聊天记录
WhatsApp客户端 -> WhatsApp集成/API -> 会员系统后台: 2. 查询会员信息
会员系统后台 -> WhatsApp集成/API -> WhatsApp客户端: 2. 查询结果(提示消息 + H5页面地址)